batch_size: 32
bps_dim: 256
d_k: 256
d_model: 512
d_v: 256
data_root_folder: ../data
device: '0'
entity: none
eval_save_path: null
exp_name: grab_h2o_bps256
for_quant_eval: false
learning_rate: 0.0002
load_last_ckpt: true
load_num: null
milestone: null
multi_task: true
n_dec_layers: 4
n_head: 4
project: ./runs_grab
save_and_sample_every: 10000
save_dir: ./runs_grab/grab_h2o_bps256
split_train_val: true
test_sample_res: false
token_obj_geom: true
use_all_data: true
use_bps_info: true
use_human_contact_dist: true
use_object_split: false
use_quat: true
w_humanContactDist: 0.5
wandb_pj_name: interact_grab_h2o
window: 120
