batch_size: 32
bps_dim: 256
checkpoint: ''
cond_mode: mixed
correct_data: false
d_k: 256
d_model: 512
d_v: 256
data_root_folder: ../data
device: '0'
entity: none
eval_save_path: null
exp_name: grab_o2h_markerVectorDist_bps256
for_quant_eval: false
fullbody_checkpoint: ''
fullbody_exp_name: stage2_exp_out
learning_rate: 0.0002
load_last_ckpt: false
load_num: null
milestone: null
motion_rep: marker
multi_task: true
n_dec_layers: 4
n_head: 4
project: ./runs_grab
run_whole_pipeline: false
save_and_sample_every: 10000
save_dir: ./runs_grab/grab_o2h_markerVectorDist_bps256
seperate_obj_contact: false
test_sample_res: false
test_sample_res_on_train: false
use_all_data: true
use_bps_info: true
use_gt_hand_for_eval: false
use_human_contact_dist: true
use_human_contact_info: false
use_human_contact_vec: true
use_obj_contact_info: false
use_object_split: true
w_contactDist: null
w_contactLabel: null
w_contactVec: null
wandb_pj_name: interact_grab_o2h
window: 120
